version: '3.8'

services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - '27020:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - network-example

  mongodb-express-example:
    image: mongo-express:latest
    container_name: mongodb-express-example
    ports:
      - '8082:8081'
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb-example
    networks:
      - network-example
    depends_on:
      - mongodb-example

networks:
  network-example:
    name: network-example
    driver: bridge
