version: '3.8'

services:
  nginx-example:
    container_name: nginx-example
    image: nginx:latest
    ports:
      - '8080:80'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100m
        reservations:
          cpus: '0.25'
          memory: 50M
