version: '3.8'

services:
  mongo-example:
    image: mongo:latest
    container_name: mongo-example
    ports:
      - 27015:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - network-example

networks:
  network-example:
    name: network-example
    driver: bridge
